/* Generated By:JavaCC: Do not edit this line. TestTreeTreeConstants.java Version 5.0 */
package Test;

public interface TestTreeTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTOPERATOR = 1;
  public int JJTOPERAND = 2;


  public String[] jjtNodeName = {
    "Expression",
    "Operator",
    "Operand",
  };
}
/* JavaCC - OriginalChecksum=a39d19885efc2270118d68903e74a380 (do not edit this line) */
