/* Generated By:JJTree&JavaCC: Do not edit this line. TestTreeConstants.java */
package Test;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TestTreeConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGITS = 2;
  /** RegularExpression Id. */
  int PLUS = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<DIGITS>",
    "\"+\"",
  };

}
