/* Generated By:JavaCC: Do not edit this line. TestTreeVisitor.java Version 5.0 */
package Test;

public interface TestTreeVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTOperator node, Object data);
  public Object visit(ASTOperand node, Object data);
}
/* JavaCC - OriginalChecksum=a2a86879a20717151b3bdb0b07ff8744 (do not edit this line) */
