/* Generated By:JJTree: Do not edit this line. ASTGREATER_THAN_OR_EQUALS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTGREATER_THAN_OR_EQUALS extends SimpleNode {
  public ASTGREATER_THAN_OR_EQUALS(int id) {
    super(id);
  }

  public ASTGREATER_THAN_OR_EQUALS(TypeScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TypeScriptParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4f7b564b893221e080d2f4c9ac1040d4 (do not edit this line) */
