/* Generated By:JJTree: Do not edit this line. ASTskip_until_new_line.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTskip_until_new_line extends SimpleNode {
  public ASTskip_until_new_line(int id) {
    super(id);
  }

  public ASTskip_until_new_line(PclParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PclParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0bfb64c96cd334ba322ae3426ac39f5a (do not edit this line) */
