/* Generated By:JavaCC: Do not edit this line. TypeScriptParserTreeConstants.java Version 5.0 */
package wci.frontend;

public interface TypeScriptParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTBOOLEAN_OP = 1;
  public int JJTLESS_THAN = 2;
  public int JJTGREATER_THAN = 3;
  public int JJTLESS_THAN_OR_EQUALS = 4;
  public int JJTGREATER_THAN_OR_EQUALS = 5;
  public int JJTEQUALITY = 6;
  public int JJTNOT_EQUALS = 7;
  public int JJTOR = 8;
  public int JJTAND = 9;
  public int JJTCONDITION = 10;
  public int JJTIF_BODY = 11;
  public int JJTIF_STMT = 12;
  public int JJTIF_PART = 13;
  public int JJTELSE_PART = 14;
  public int JJTWHILE_NODE = 15;
  public int JJTVOID = 16;
  public int JJTCOMPOUND_STMT = 17;
  public int JJTPRINTLN = 18;
  public int JJTPUREFUNCTION = 19;
  public int JJTFUNCTIONDECLARATION = 20;
  public int JJTFUNCTION_INVOCATION = 21;
  public int JJTDECLARATION = 22;
  public int JJTASSIGNMENT = 23;
  public int JJTIDENTIFIER = 24;
  public int JJTADD = 25;
  public int JJTSUBTRACT = 26;
  public int JJTMULTIPLY = 27;
  public int JJTDIVIDE = 28;
  public int JJTBOOLEAN_NODE = 29;
  public int JJTNUMBER = 30;
  public int JJTSTRING = 31;
  public int JJTERROR = 32;


  public String[] jjtNodeName = {
    "program",
    "boolean_op",
    "LESS_THAN",
    "GREATER_THAN",
    "LESS_THAN_OR_EQUALS",
    "GREATER_THAN_OR_EQUALS",
    "EQUALITY",
    "NOT_EQUALS",
    "OR",
    "AND",
    "condition",
    "if_body",
    "if_stmt",
    "if_part",
    "else_part",
    "while_node",
    "void",
    "Compound_stmt",
    "println",
    "PureFunction",
    "FunctionDeclaration",
    "Function_invocation",
    "declaration",
    "Assignment",
    "identifier",
    "add",
    "subtract",
    "multiply",
    "divide",
    "boolean_node",
    "number",
    "string",
    "error",
  };
}
/* JavaCC - OriginalChecksum=ec0a56413c83dce16f69aef267ffccb4 (do not edit this line) */
