/* Generated By:JavaCC: Do not edit this line. TypeScriptParserVisitor.java Version 5.0 */
package wci.frontend;

public interface TypeScriptParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTprogram node, Object data);
  public Object visit(ASTboolean_op node, Object data);
  public Object visit(ASTLESS_THAN node, Object data);
  public Object visit(ASTGREATER_THAN node, Object data);
  public Object visit(ASTLESS_THAN_OR_EQUALS node, Object data);
  public Object visit(ASTGREATER_THAN_OR_EQUALS node, Object data);
  public Object visit(ASTEQUALITY node, Object data);
  public Object visit(ASTNOT_EQUALS node, Object data);
  public Object visit(ASTOR node, Object data);
  public Object visit(ASTAND node, Object data);
  public Object visit(ASTcondition node, Object data);
  public Object visit(ASTif_body node, Object data);
  public Object visit(ASTif_stmt node, Object data);
  public Object visit(ASTif_part node, Object data);
  public Object visit(ASTelse_part node, Object data);
  public Object visit(ASTwhile_node node, Object data);
  public Object visit(ASTCompound_stmt node, Object data);
  public Object visit(ASTprintln node, Object data);
  public Object visit(ASTPureFunction node, Object data);
  public Object visit(ASTFunctionDeclaration node, Object data);
  public Object visit(ASTFunction_invocation node, Object data);
  public Object visit(ASTdeclaration node, Object data);
  public Object visit(ASTAssignment node, Object data);
  public Object visit(ASTidentifier node, Object data);
  public Object visit(ASTadd node, Object data);
  public Object visit(ASTsubtract node, Object data);
  public Object visit(ASTmultiply node, Object data);
  public Object visit(ASTdivide node, Object data);
  public Object visit(ASTboolean_node node, Object data);
  public Object visit(ASTnumber node, Object data);
  public Object visit(ASTstring node, Object data);
  public Object visit(ASTerror node, Object data);
}
/* JavaCC - OriginalChecksum=de1a8ee62c5e9ca9d067dbd535611ffd (do not edit this line) */
