/* Generated By:JJTree: Do not edit this line. ASTMoveForward.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMoveForward extends SimpleNode {
  public ASTMoveForward(int id) {
    super(id);
  }

  public ASTMoveForward(Logo p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(LogoVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e706017747d9052803422322011c56c8 (do not edit this line) */
