/* Generated By:JavaCC: Do not edit this line. LogoVisitor.java Version 5.0 */
public interface LogoVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTMoveForward node, Object data);
  public Object visit(ASTTurnRight node, Object data);
  public Object visit(ASTError node, Object data);
}
/* JavaCC - OriginalChecksum=1dd62ecd6a5b7a517778a77bc5bbdbdb (do not edit this line) */
