/* Generated By:JavaCC: Do not edit this line. LogoTreeConstants.java Version 5.0 */
public interface LogoTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTMOVEFORWARD = 1;
  public int JJTTURNRIGHT = 2;
  public int JJTERROR = 3;
  public int JJTVOID = 4;


  public String[] jjtNodeName = {
    "Program",
    "MoveForward",
    "TurnRight",
    "Error",
    "void",
  };
}
/* JavaCC - OriginalChecksum=b1daf5808e0affa3488e8eb9a7529d83 (do not edit this line) */
