/* Generated By:JJTree&JavaCC: Do not edit this line. LogoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LogoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int FORWARD = 2;
  /** RegularExpression Id. */
  int RIGHT = 3;
  /** RegularExpression Id. */
  int DIGITS = 4;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int ERROR = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"FORWARD\"",
    "\"RIGHT\"",
    "<DIGITS>",
    "<EOL>",
    "<ERROR>",
  };

}
