/* Generated By:JJTree: Do not edit this line. ASTGREATER_THAN.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=wci.intermediate.icodeimpl.ICodeNodeImpl,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package wci.frontend;

public
class ASTGREATER_THAN extends SimpleNode {
  public ASTGREATER_THAN(int id) {
    super(id);
  }

  public ASTGREATER_THAN(TypeScriptParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(TypeScriptParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c16d73d80d545a56ad8cd0fa5e02d0f4 (do not edit this line) */
